### ISSUE TITLE
Cannot parse note "eb3"

### ISSUE THREAD

**Issue by winniehell** [justinjmoses/node-keyboard#1]
@justinjmoses What am I doing wrong here?

```
node-keyboard>sequence(c, 2, 1, 2, 2, 1, 2, 2)
[ 'c3', 'd3', 'eb3', 'f3', 'g3', 'g#3', 'a#3', 'c4' ]
node-keyboard>sequence(c, 2, 1, 2, 2, 1, 2, 2).map(play)

node_modules/node-keyboard/lib/mappers.js:14
        throw new Error(`Cannot parse note "${chunk.input}"\n`)
        ^
Error: Cannot parse note "eb3"

    at exports.play.e (node_modules/node-keyboard/lib/mappers.js:14:15)
    at Array.map (native)
    at evalmachine.<anonymous>:1:34
    at Object.exports.runInContext (vm.js:44:17)
    at REPLServer.module.exports (node_modules/node-keyboard/lib/evaluator.js:28:23)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:441:10)
    at emitOne (events.js:96:13)
    at REPLServer.emit (events.js:188:7)
node-keyboard>play('eb3');
play('eb3');
Error: Cannot parse note "eb3"

    at exports.play.e (node_modules/node-keyboard/lib/mappers.js:14:15)
    at evalmachine.<anonymous>:1:1
    at Object.exports.runInContext (vm.js:44:17)
    at REPLServer.module.exports (node_modules/node-keyboard/lib/evaluator.js:28:23)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:441:10)
    at emitOne (events.js:96:13)
    at REPLServer.emit (events.js:188:7)
    at REPLServer.Interface._onLine (readline.js:224:10)
```

**Comment by jjgonecrypto** [comment]
Hi @winniehell, which version of node are you on? It requires node 6+ for Proxy. Though I don't suspect that's your problem. Does it happen on a fresh run?

![issue](https://cloud.githubusercontent.com/assets/799038/20190115/1ba37002-a74e-11e6-9fd2-356bf23a96e6.gif)

**Comment by jjgonecrypto** [comment]
Did it download the soundfonts after install? That is, have you heard it play other notes?

**Comment by winniehell** [comment]
@justinjmoses That was a fast reply, awesome! :smile: 

I am running node v6.2.2 and node-keyboard 3.7.0.

```
['c', 'e', 'a'].map(play);
```

plays nicely without any problems.

**Comment by winniehell** [comment]
Unlike you, I don't have that `MIDI not detected. Disabling support.` message. Not sure if that is relevant.

**Comment by jjgonecrypto** [comment]
Does `play(eb3)` work? (no strings). What about `play(ds3)`? Or `play('d#3')`? (MIDI support shouldn't matter here)

**Comment by winniehell** [comment]
@justinjmoses I just cloned your repository and ran `npm install`, just to be sure I have the most recent version.

Soundfonts were installed without problems:

```
Downloading soundfonts...
(cloning git@github.com:gleitz/midi-js-soundfonts.git to node-keyboard/midi-js-soundfonts)
Download complete.
```

```
node-keyboard>play(eb3);
play(eb3);
Error: Cannot parse note "eb3"

    at exports.play.e (node-keyboard/lib/mappers.js:14:15)
    at evalmachine.<anonymous>:1:1
    at Object.exports.runInContext (vm.js:44:17)
    at REPLServer.module.exports (node-keyboard/lib/evaluator.js:28:23)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:441:10)
    at emitOne (events.js:96:13)
    at REPLServer.emit (events.js:188:7)
    at REPLServer.Interface._onLine (readline.js:224:10)
node-keyboard>play(ds4);
play(ds4);
Error: Cannot parse note "d#4"

    at exports.play.e (node-keyboard/lib/mappers.js:14:15)
    at evalmachine.<anonymous>:1:1
    at Object.exports.runInContext (vm.js:44:17)
    at REPLServer.module.exports (node-keyboard/lib/evaluator.js:28:23)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:441:10)
    at emitOne (events.js:96:13)
    at REPLServer.emit (events.js:188:7)
    at REPLServer.Interface._onLine (readline.js:224:10)
```

**Comment by jjgonecrypto** [comment]
Hmmm. Thanks for bearing with me - this is the first issue from someone else, so there's some work to do here =) 

I'm guessing node-keyboard can't find the MP3 file, which is unusual. 

If you comment out this line: https://github.com/justinjmoses/node-keyboard/blob/master/lib/mappers.js#L14 - what error do you see?

**Comment by winniehell** [comment]
> If you comment out this line - what error do you see?

@justinjmoses Nothing... :smile: 

```
node-keyboard>play(ds4);
node-keyboard>play(eb3);
```

(so that is good, I assume)

...but I also don't hear anything. :cry:

**Comment by winniehell** [comment]
@justinjmoses I replaced the line with `console.error(e);` and now I get:

```
node-keyboard>play(eb3);
Error: Cannot play "eb3"
    at Object.play (/home/winnie/Projects/nodejs/node-keyboard/lib/instruments.js:42:19)
    at exports.play.e (/home/winnie/Projects/nodejs/node-keyboard/lib/mappers.js:12:28)
    at evalmachine.<anonymous>:1:1
    at Object.exports.runInContext (vm.js:44:17)
    at REPLServer.module.exports (/home/winnie/Projects/nodejs/node-keyboard/lib/evaluator.js:28:23)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:441:10)
    at emitOne (events.js:96:13)
    at REPLServer.emit (events.js:188:7)
```

**Comment by winniehell** [comment]
> I'm guessing node-keyboard can't find the MP3 file, which is unusual.

@justinjmoses Gotcha!

```
n.path: midi-js-soundfonts/FluidR3_GM/acoustic_grand_piano-mp3/EB3.mp3
```

```
$ ls midi-js-soundfonts/FluidR3_GM/acoustic_grand_piano-mp3/E*.mp3
...
midi-js-soundfonts/FluidR3_GM/acoustic_grand_piano-mp3/Eb3.mp3
...
```

The `b` needs to be lower-case.

**Comment by winniehell** [comment]
It's working! :tada: 

```
node-keyboard>play(eb3);
{ input: 'eb3',
  kill: [Function],
  played: 'acoustic_grand_piano: 𝄞 ♩ eb3' }
```

I'll post a pull request&mdash;thanks a lot for the help! :+1: :smiley:

**Comment by jjgonecrypto** [comment]
Ah your OS is case-sensitive. I'd not tested it under other environments. What's your OS?

**Comment by winniehell** [comment]
> What's your OS?

It's a Linux. :wink:

**Comment by jjgonecrypto** [comment]
Thanks for the PR. Lets discuss it over there.
