### ISSUE TITLE
Soundfonts doesn't install

### ISSUE THREAD

**Issue by N0bl3** [justinjmoses/node-keyboard#3]
As such, the software cannot start. Error message:

```
PS C:\Users\Admin> node-keyboard
fs.js:870
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\Admin\AppData\Roaming\npm\node_modules\node-keyboard\midi-js
-soundfonts\FluidR3_GM'
    at Object.fs.readdirSync (fs.js:870:18)
    at Object.get all (C:\Users\Admin\AppData\Roaming\npm\node_modules\node-keyboard\lib\instruments.js:14:26)
    at Object.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\node-keyboard\lib\mappers.js:48:34)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
PS C:\Users\Admin>
```

**Comment by jjgonecrypto** [comment]
When you ran `npm install` - did it clone the soundfonts library? It's a `postinstall` script in `npm` so it should have told you it was downloading. 

Alternatively, if you run `node install` in the root of the app, it will do the install again for you. (The install will create the path `./midi-js-soundfonts/FluidR3_GM`

**Comment by jjgonecrypto** [comment]
@N0bl3 I will close this now. But if you still have an issue please comment and I can reopen.
